[project]
name = "tk-fd-search"
version = "1.1.0"
description = "A simple GUI wrapper for the 'fd' command."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cx-freeze>=8.3.0",
    "ttkbootstrap>=1.13.10",
]
